language: python
python:
  - '3.5'
  - '3.6'
  - 3.7-dev
  - nightly
install:
  - pip install .
  - pip install -r test_requirements.txt
script:
  - nosetests
deploy:
  provider: pypi
  user:
    secure: s54NQ8JCdxWqOtaAIVKGjYSTLoz0vyB8XssBuDuchxS1T0yfVyl6ggbb7V8gNxGPWej86+sYmsIRdMXoY4w1DUzgMeBcfpzfrxzVcJWY+YTriRb189A+QsZWzS+YRanQNu4NWrQl5bXZ7apksjC3LIqUBTtN35sTWITiMgBIhY2RW5oDXStOtDw5ECkRU6+BSgEk7k0HekZBLzBUlrOQ52ptIIhLJi6JsI5H11IRZ7qDaOZ4+b52g+q5qOtg3ZQUBRef3GOEeeqRf9CVLHYQGHyxd3UKi2w7MeO3SCaRiJpRyRBdat8thQrtZIbfWFo7BJNbXKJN9yiRPFZJC2DGu1MvTPiME4y7QcJXNBDoblC4sllpdvH/tyRsqISP3kYJiOrWhvqM6EYbftXq1ZDzLR2Anwv/mutpj7upqZi+bD1ygxKOK+cJSWwrntAf605Ad0wSxh9qDl/BJQFB5N+R6nEZHfa127ZjxbuwdK2OFuAd8Tukcwbx9HmKzKWuB+F2b5f/G0//crGd1yYhwAMwRYi1XCeULFvSJNHgX9Mw/lmGLE+M4YebOHlxbJCETCP/j5S8QCCLdJi+6K7eXwuecebFneB/8ASkzzU7yusRJrUvOC8JrkYHR0cd++qFUWZLPcqWhjmJKx55xhMvKE4MIMPiNFJWF2XVmIVOc0KNHgw=
  password:
    secure: UGrIyslMNS/QtJkJhKPptMgeeF9thHBQaP0qY/NQwa/UnUz4eX0n65w2vaSm2Q6+v5nJ+ecBKKyGVuP3xbob097yhVni1fxRDlZIybWLX3JmPCjtx+XqpBarA4NZXZ6DQJ6pJb4LXNZpIsFIu/M3EodDftB56g81USYt04OPOAVM0aePogBcMZVF+VVHPgZFMvm09SUYZCpUeKq9mLGDkJ74vTAh4d5MfgO9iChW9OlhC2IfYu2jmR4wXC48YJSlzUB5o3rRn1IUqnmVWK41Us/bH6IWpuLE8SaVX2Tk93pRCfxygvnXMK220ESobPbEhcqqYdWUhvjOYeTyw6PqYbkQEKZ0SE08jZIY1c/Z5ZZN9bgiigH2PSqtFlN228RBoDV3d1zXkHUDSHCOF4H8yilXHWsn7CPlo5mIAdAggvch6PyQy087jodA7WOLsSYPuJWXt3dpyPdXP1S0OEjfUm7jRH3PFe9kjdT/EdAc6Mu9XcFr6NXnePzFzpT5eDBI7Z5T+NS7eAqA0sdU5hm9qc2rJsfgZzz4k9g2i8WhYzMDrGg0q9H66YnVRva4d8X5Rf60SjQnJHtrOGdmEUqsW96d4dlwK4y/zE4cut/PrQ5tUix+AYJWC0mqJ6i5lNhWdesPOa4jXlWdMm8vAib/iTbCxrUA//ePOrAakz/GYXs=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true
